View(melb_data)
nrow(melb_data)
class(melb_data$Price)
mean(melb_data$Price)
summary(melb_data$Price)
class(melb_data$Date)
melb_data$Date <- as.Date(melb_data$Date, format = "%d-%m-%Y")
class(melb_data$Date)
melb_data$Date <- format(melb_data$Date, "%d-%m-%Y")
class(melb_data$Date)
melb_data$Date_formatted<-melb_data$Date
class(melb_data$Date_formatted)
melb_data$Date_formatted<-format(melb_data$Date_formatted, "%d-%m-%Y")
melb_data$Date_formatted <- as.Date(melb_data$Date_formatted, format = "%d-%m-%Y")
melb_data$Date_formatted <- format(melb_data$Date_formatted, "%d-%m-%Y")
melb_data_subset<- subset(melb_data,format(Date, "%Y") == "2017" & format(Date, "%m") %in% c("01", "02", "03"))
class(melb_data$Date)
library(tidyverse)
install.packages("tidyverse")
library(tidyverse)
class(melb_data$Date)
df$Date <- as.Date(df$Date, format="%d/%m/%Y")
melb_data$Date <- as.Date(melb_data$Date, format="%d/%m/%Y")
class(melb_data$Date)
melb_data_subset<- subset(melb_data,format(Date, "%Y") == "2017" & format(Date, "%m") %in% c("01", "02", "03"))
class(melb_data_subset$Date)
